### ISSUE TITLE
could we go back to having regular releases of Fauxhai?

### ISSUE THREAD

**Issue by juliandunn** [customink/fauxhai#133]
Hey Seth and friends,

I was wondering if we could go back to having regular releases of the Fauxhai gem to pick up all the OS definitions.

I realize that [mocker.rb](https://github.com/customink/fauxhai/blob/master/lib/fauxhai/mocker.rb) has the ability to fetch updated platforms off GitHub, but this doesn't really work when I'm on a plane and trying to write unit tests for platforms that don't exist in the released Gem (actual situation last week).

Thoughts?

**Comment by sethvargo** [comment]
Hey Julian,

I can release a new version, but Fauxhai should be caching the result on disk. So, at most, it should be downloaded once and then saved. If you're experiencing different behavior, please let me know. 

For what it's worth, we have never released a new version of Fauxhai when new OSes are added - they have always been automatically downloaded :smile:.

I will release a new version shortly, but I don't think it's feasible to cut a new release for each new OS that is added. Does that make sense?

**Comment by juliandunn** [comment]
Yeah, my use case was that I was writing tests for weird-ass platforms that I'd never used before while on an airplane.

By "regularly" I meant that a few times a year would be sufficient. Thanks Seth!

**Comment by sethvargo** [comment]
2.3.0 is out.

**Comment by kramvan1** [comment]
Since I just added the centos 7.1 support, would like to see a new version so I can pick that up with my automated build process, right now I get the latest version at 2.3.0.    @sethvargo you state above about "automatically downloaded", can you clarify what you mean by that?
