### ISSUE TITLE
OpenURI based fetching should rescue socket errors too

### ISSUE THREAD

**Issue by coderanger** [customink/fauxhai#136]
Happens when not online so DNS resolution fails. Also the fact that Fauxhai talks to the internet at all makes me suuuuper nervous, now that most platforms are filled out maybe it would be good to remove that code?

**Comment by sethvargo** [comment]
@coderanger I don't want to release a new Fauxhai any time a new PR comes in. It has been really successful thus far and talks over HTTPS to GitHub. I would be okay adding an envvar to disable though.

**Comment by coderanger** [comment]
A global var I could set in my spec helper would work, env var or just Fauxhai.disable_http_loading = true or somesuch.

**Comment by sethvargo** [comment]
Cool cool. I'll gladly review a PR for that, but I doubt I'll implement it myself :smile:

**Comment by coderanger** [comment]
:+1: Want a separate PR for the socketerror thingy?

**Comment by sethvargo** [comment]
You can use the same one if you'd like - I'm flexible like that

**Comment by tas50** [comment]
We now have a config value to disable fetching from Github for those in airgapped environments.
