### ISSUE TITLE
redhat and centos 7.1 support?

### ISSUE THREAD

**Issue by kramvan1** [customink/fauxhai#138]
Need redhat centos 7.1 support.

https://access.redhat.com/support/policy/updates/errata

**Comment by sethvargo** [comment]
Fauxhai is a community-based project and relies on community-supplied data. If you would like to submit this data to Fauxhai, please consult the README for instructions.

**Comment by kramvan1** [comment]
Thx, here's the PR: https://github.com/customink/fauxhai/pull/139
