### ISSUE TITLE
Bump gem version

### ISSUE THREAD

**Issue by scassiba** [customink/fauxhai#141]
Ohai

With the recent rhel7.1 update in [#139](https://github.com/customink/fauxhai/pull/139), a new version of the gem needs to be released to rubygems. Would you please cut a new gem?

Thanks!

**Comment by sethvargo** [comment]
New versions are automatically downloaded by fauxhai as they become available. Just specify the os and version and it will be downloaded and cached.

**Comment by scassiba** [comment]
Thank you for the clarification. There is an issue, however, with the version on rubygems.org. It does not contain 7.1.json, which is needed as RHEL7.0 does not have EUS/LTS

**Comment by sethvargo** [comment]
@scassiba correct. As I said above, Fauxhai will [attempt to download the version from GitHub](https://github.com/customink/fauxhai/blob/17365488b9b2a85dd4f469cc9f4ccc33b88806c1/lib/fauxhai/mocker.rb#L55-L76). Just use rhel 7.1 in fauxhai/chefspec as you normally would and it will be downloaded automatically when fauxhai runs.
