### ISSUE TITLE
CentOS 6.2 does not include platform family

### ISSUE THREAD

**Issue by rylarson** [customink/fauxhai#154]
For some reason the CentOS 6.2 json file does not include `platform_family`. I was under the impression that ohai would always assign a family.

https://github.com/customink/fauxhai/blob/master/lib/fauxhai/platforms/centos/6.2.json

**Comment by tas50** [comment]
I've recaptured all CentOS 6 releases using the latest Ohai so this will include platform_family now.  Once a new release of the gem is out you'll start to get 6.2 with platform family.
