### ISSUE TITLE
Ready for a new release

### ISSUE THREAD

**Issue by tas50** [customink/fauxhai#180]
All major platform versions have been regenerated with the current Ohai release.  Ready to get a new gem out so people can use the new dumps

**Comment by trinitronx** [comment]
:+1: the `mac_os_x`/`10.11.1` dump!  Without new release [I get this][1].  With latest fauxhai it works!

[1]: https://travis-ci.org/trinitronx/lyraphase_workstation/builds/91751447#L200

**Comment by bdangit** [comment]
:+1:  would be nice to have a fauxhai to support redhat 7.1

**Comment by andrewhsu** [comment]
:+1:  yes, me wants 7.1

**Comment by sethvargo** [comment]
@tas50 you should be able to release now :smile:

**Comment by tas50** [comment]
@sethvargo Doesn't look like I have the rubygems privs

**Comment by sethvargo** [comment]
Fixed
