### ISSUE TITLE
Generated routes attribute format is incorrect

### ISSUE THREAD

**Issue by Annih** [customink/fauxhai#216]
Hello,

Fauxhai runner is [generating network routes as a Hash](https://github.com/customink/fauxhai/blob/a616c6aa9e2e7e6d9825a579a00b8d6e15484205/lib/fauxhai/runner.rb#L193), but [ohai is now using an array - since 2012!](https://github.com/chef/ohai/commit/35e1a627401152d9ad805abb4ebe1ba3ab6e2e1e#diff-c8ac395a03635d8ecadf1128ead76abaL231).
We should fix the runner - pretty easy - but also all linux fauxhai!

Regards,

Annih

**Comment by tas50** [comment]
If you want to open a PR with a change here:

https://github.com/customink/fauxhai/blob/master/lib/fauxhai/runner.rb#L193

Just make sure to show from real Ohai data what the format looks like now.
