### ISSUE TITLE
Centos / RHEL 7.3 missing

### ISSUE THREAD

**Issue by artem-sidorenko** [customink/fauxhai#263]
Centos / RHEL 7.3 are missing

I can create a PR if usage of bento boxes as source would be fine for you

**Comment by iamthemuffinman** [comment]
Looks like it was added here: https://github.com/customink/fauxhai/commit/736aa340c0154b1141861af96870dd9e35a353eb

**Comment by tas50** [comment]
CentOS 7.3 is up on master and I'll get it released to the gem in the next few days
